### ISSUE TITLE
Build failure since 0b964558d19f22dc2c0c47be450820e7bd930d3d

### ISSUE THREAD

**Issue by dburkart** [dburkart/vibix#190]
```
warning: `vibix` (lib) generated 1 warning
error[E0432]: unresolved import `vibix::mem::vma`
  --> kernel/tests/smep_smap.rs:21:17
   |
21 | use vibix::mem::vma::{Vma, VmaKind};
   |                 ^^^ could not find `vma` in `mem`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `vibix` (test "smep_smap") due to 1 previous error
warning: build failed, waiting for other jobs to finish...
Error: "command failed: exit status: 101"
Error: Process completed with exit code 1.
```
